### ISSUE TITLE
Avoid logging into syslog (question)

### ISSUE THREAD

**Issue by k-sartor** [azlux/log2ram#106]
Hi,
i would like to know if there is a way to turn off loging of log2ram into syslog file while it has its own log file.

I tried by adding a rule in rsyslog.conf
:msg, contains, "log2ram" stop
but it does not work.
Thank you

**Comment by SargonofAssyria** [comment]
This works for me:
`
if $programname == 'log2ram' then /dev/null
& stop
`

**Comment by k-sartor** [comment]
Thank you. 
However, in this case, it is required to see in syslog when log2ram have been restarted (by systemd) and in the log2ram.log the files synced.
Is there any way to put the date of file syning in log2ram.log?

**Comment by azlux** [comment]
@k-sartor new changes will use systemd-timer. So you will have everything into systemd logs instead of syslog.

**Comment by azlux** [comment]
A new version without cron have been release. This issue should be fix because I now use systemd-timer
