### ISSUE TITLE
log2ram don't work on read-only filesystem

### ISSUE THREAD

**Issue by organic-ip** [azlux/log2ram#109]
Thanks for this nice project.

I adapt log2ram to work even on a readonly filesystem on host.

[log2ram-on-readonl-file-system.diff.zip](https://github.com/azlux/log2ram/files/4624679/log2ram-on-readonl-file-system.diff.zip)

Best Regards.
Gerald

**Comment by fletort** [comment]
you should make a pull request from your fork ?

**Comment by organic-ip** [comment]
it's done :-)
