### ISSUE TITLE
rsync warning

### ISSUE THREAD

**Issue by Sucuarana** [azlux/log2ram#126]
Hi,

I have received the following warnings in the syslog:

`Sep 16 00:00:00 pi-hole log2ram[15013]: file has vanished: "/var/log/log2ram.log.1.gz"`
 `Sep 16 00:00:00 pi-hole rsync warning: some files vanished before they could be transferred (code 24) at main.c(1207) [sender=3.1.3]`

I decided to advance the execution of the service through the command `systemctl edit log2ram-daily.timer` and adding the lines below:

```
[Timer]
OnCalendar=*-*-* 23:58:00
```

My logic is that all daily services are performed at the same time (00:00:00). Therefore, it may happen that something is lost in the process.

Apparently, after editing, I didn't get the warning again:

_syslog.1_
`Sep 16 23:58:14 pi-hole systemd[1]: Started Daily Log2Ram writing activities.`
`Sep 16 23:58:14 pi-hole systemd[1]: Reloading Log2Ram.`
`Sep 16 23:58:14 pi-hole log2ram[5483]: building file list ... done`
`Sep 16 23:58:14 pi-hole log2ram[5483]: auth.log`
`Sep 16 23:58:14 pi-hole log2ram[5483]: daemon.log`
`Sep 16 23:58:14 pi-hole log2ram[5483]: debug`
`Sep 16 23:58:14 pi-hole log2ram[5483]: kern.log`
`Sep 16 23:58:14 pi-hole log2ram[5483]: log2ram.log`
`Sep 16 23:58:14 pi-hole log2ram[5483]: messages`
`Sep 16 23:58:14 pi-hole log2ram[5483]: pihole-FTL.log`
`Sep 16 23:58:14 pi-hole log2ram[5483]: pihole.log`
`Sep 16 23:58:15 pi-hole log2ram[5483]: syslog`
`Sep 16 23:58:15 pi-hole log2ram[5483]: user.log`
`Sep 16 23:58:15 pi-hole log2ram[5483]: wtmp`
`Sep 16 23:58:15 pi-hole log2ram[5483]: lighttpd/access.log`
`Sep 16 23:58:15 pi-hole log2ram[5483]: lighttpd/error.log`
`Sep 16 23:58:15 pi-hole log2ram[5483]: sent 2,171,074 bytes  received 12,948 bytes  1,456,014.67 bytes/sec`
`Sep 16 23:58:15 pi-hole log2ram[5483]: total size is 10,158,304  speedup is 4.65`
`Sep 16 23:58:15 pi-hole systemd[1]: Reloaded Log2Ram.`
`Sep 16 23:58:15 pi-hole systemd[1]: log2ram-daily.service: Succeeded.`

_syslog_
`Sep 17 00:00:14 pi-hole systemd[1]: Started Daily Log2Ram writing activities.`
`Sep 17 00:00:14 pi-hole systemd[1]: Starting Daily man-db regeneration...`
`Sep 17 00:00:14 pi-hole systemd[1]: Starting Rotate log files...`
`Sep 17 00:00:14 pi-hole systemd[1]: Reloading Log2Ram.`
`Sep 17 00:00:14 pi-hole log2ram[5538]: building file list ... done`
`Sep 17 00:00:14 pi-hole log2ram[5538]: ./`
`Sep 17 00:00:14 pi-hole rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="406" x-info="https://www.rsyslog.com"] rsyslogd was HUPed`
`Sep 17 00:00:14 pi-hole rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="406" x-info="https://www.rsyslog.com"] rsyslogd was HUPed`
`Sep 17 00:00:14 pi-hole log2ram[5538]: auth.log`
`Sep 17 00:00:14 pi-hole log2ram[5538]: daemon.log`
`Sep 17 00:00:14 pi-hole systemd[1]: logrotate.service: Succeeded.`
`Sep 17 00:00:14 pi-hole systemd[1]: Started Rotate log files.`
`Sep 17 00:00:14 pi-hole log2ram[5538]: log2ram.log`
`Sep 17 00:00:14 pi-hole log2ram[5538]: pihole-FTL.log`
`Sep 17 00:00:14 pi-hole log2ram[5538]: pihole-FTL.log.1`
`Sep 17 00:00:14 pi-hole log2ram[5538]: pihole-FTL.log.2.gz`
`Sep 17 00:00:14 pi-hole log2ram[5538]: pihole-FTL.log.3.gz`
`Sep 17 00:00:14 pi-hole log2ram[5538]: pihole.log`
`Sep 17 00:00:14 pi-hole log2ram[5538]: pihole.log.1`
`Sep 17 00:00:15 pi-hole log2ram[5538]: pihole.log.2.gz`
`Sep 17 00:00:15 pi-hole log2ram[5538]: pihole.log.3.gz`
`Sep 17 00:00:15 pi-hole log2ram[5538]: pihole.log.4.gz`
`Sep 17 00:00:15 pi-hole log2ram[5538]: pihole.log.5.gz`
`Sep 17 00:00:15 pi-hole log2ram[5538]: syslog`
`Sep 17 00:00:15 pi-hole log2ram[5538]: sent 4,345,185 bytes  received 35,348 bytes  2,920,355.33 bytes/sec`
`Sep 17 00:00:15 pi-hole log2ram[5538]: total size is 6,440,798  speedup is 1.47`
`Sep 17 00:00:15 pi-hole systemd[1]: Reloaded Log2Ram.`
`Sep 17 00:00:15 pi-hole systemd[1]: log2ram-daily.service: Succeeded.`
`Sep 17 00:00:16 pi-hole systemd[1]: man-db.service: Succeeded.`
`Sep 17 00:00:16 pi-hole systemd[1]: Started Daily man-db regeneration.`

Anyway, I know that my change is not the correct way to deal with the situation and, therefore, it has already been undone.

**Comment by azlux** [comment]
Fix with https://github.com/azlux/log2ram/commit/c92e706d2d9811befbd86fa31cb188eda03290db
Thank for the report, this one is hard to see.
