### ISSUE TITLE
Question - Can log2ram flush to an external drive?

### ISSUE THREAD

**Issue by jouellnyc** [azlux/log2ram#127]
Tremendous Effort.

Is it possible to flush logs to an external ssd device instead of the mounted microsd?
This post suggests as much. https://ostechnix.com/how-to-write-log-files-in-ram-using-log2ram-in-linux/

**Comment by azlux** [comment]
Sorry, I've forgot your issue. My bad.
If you want logs into a separated SSD, make a mount of `/var/log` into your SSD. You don't need `log2ram`for that.
You can directly use `fstab`
