### ISSUE TITLE
Question: Does log2ram work together with fail2ban?

### ISSUE THREAD

**Issue by smokemyshoes** [azlux/log2ram#128]
Hi

Maybe a totall noob question but nevertheless.... Will fail2ban work after using log2ram?

If yes, will it require any (re-)configuration of fail2ban?

Many thanks in advance!

**Comment by azlux** [comment]
Hi,
You don't need to make changes on fail2ban.

**Comment by smokemyshoes** [comment]
Thanks for the swift reply. I'll give it a try.
