### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by smokemyshoes** [azlux/log2ram#131]
Hi

I have three questions, probably rather easy ones...

1) Do you see any issues in installing log2ram after pi-hole and pivpn?
2) I'm running a nightly rsync backup-script on my rpi. Is it advised to stop the log2ram service before performing the backup?
3) Will `service log2ram stop` force it to write to disk before shutting down?

Thanks in advance

**Comment by azlux** [comment]
I personnally use log2ram+pihole+pivpn without any issue.
If you want to flush all log in disk, you can `systemctl reload log2ram.service`. Not sure it's necessary because you backup will also copy `/var/log` as a standard folder even if log2ram put theses data in RAM.
