### ISSUE TITLE
ERROR: RAM disk for "/var/hdd.log/" too small. Can't sync

### ISSUE THREAD

**Issue by sharicov** [azlux/log2ram#133]
doesn't start
raspberry pi 4 8GB
Solved using following solution: https://github.com/azlux/log2ram/issues/90

**Comment by MegaV0lt** [comment]
Increase $SIZE in your conf.
To get actal size of log do
`du -sh /var/log`
You can chanche the size to double or more of actual size because the space is dynaicaly allocated
