### ISSUE TITLE
Adding other folder

### ISSUE THREAD

**Issue by gsemet** [azlux/log2ram#135]
Hello,

Pihole stores long term storage in /etc/pihole/pihole-FTL.db, would it makes sense to move it to /var/log or have log2ram watch another folder so that this file can also use log2ram mecanism? In short, how log2ram handles binary files?

**Comment by azlux** [comment]
See https://github.com/azlux/log2ram/blob/master/log2ram.conf#L19-L21 .
I think It's not on the Readme. My bad.
