### ISSUE TITLE
Can the interval be changed to hourly?

### ISSUE THREAD

**Issue by braham2019** [azlux/log2ram#136]
The default interval to write to disk is daily (from the readme); is it possible to change this to daily or another interval ?

**Comment by azlux** [comment]
You can edit the interval as mentioned on the readme : https://github.com/azlux/log2ram#refresh-time
`systemctl edit log2ram-daily.timer` and add: 
```
[Timer]
OnCalendar= XXXX
```
complete XXXX with this doc : https://www.freedesktop.org/software/systemd/man/systemd.time.html#

**Comment by braham2019** [comment]
Thanks. I didn't know about systemd.time. Good work with log2ram
