### ISSUE TITLE
explanation of the system

### ISSUE THREAD

**Issue by boistordu** [azlux/log2ram#154]
Hi,

this is a following of https://github.com/azlux/log2ram/issues/124 for maybe a slight different usecase.
I was understanding this project as : 
mount a path in ram, so a ramdisk -> this path is empty so it is to write new logs -> at each shutdown it writes to /var/hdd.log and so at each reboot it is a clean slate and the var/log should be emptied no?
Or it reloads everytime the content of /var/hdd.log inside ? 
Because then it seems a bit counterproductive no?

**Comment by azlux** [comment]
Hi the system write the log on the real disk every days
the order is : mount a tmpfs -> copy real disk inside the tmpfs > make the system use the ram disk> write everything every day or at reboot.

Make a ram disk only get the new content is hard, there are lot of cases. So to get this project KISS, I copy everything.
It's counterproductive with the memory point of view, but herer I want to protect the SDcard. Memory handle this fine.
