### ISSUE TITLE
Why is anything other than sysinit.target listed in log2ram.service's Before= field?

### ISSUE THREAD

**Issue by spwhitton** [azlux/log2ram#161]
Hello,

Thanks for this project.  I'm trying to understand log2ram.service.  Why are there so many things listed in the Before= field?  Why is it not enough to just have sysinit.service there?

In systemd.special(7) it says

       sysinit.target
           systemd automatically adds dependencies of the types Requires= and
           After= for this target unit to all services (except for those with
           DefaultDependencies=no).

Then, for example, lighttpd.service already has After=sysinit.service, in which case listing it in log2ram.service is redundant.

Thanks!

**Comment by azlux** [comment]
Hi,
Not sure we can well manage the starting order this way.
