### ISSUE TITLE
Support for Debian 11 Bullseye

### ISSUE THREAD

**Issue by h88e22dgpeps56sg** [azlux/log2ram#170]
Since Debian 11 "_Bullseye_" is now stable, it would be really nice if you could update your [repository server](https://packages.azlux.fr/debian/) accordingly.

As a reminder: README.md would need a tiny bit of editing in the _Install_ section, too.

Thanks and have a nice day. :)

**Comment by azlux** [comment]
Hi,
It's in progress, Should be available in few minutes

**Comment by h88e22dgpeps56sg** [comment]
Works like a charm. Thanks a lot!
