### ISSUE TITLE
Best way to temporarily disable?

### ISSUE THREAD

**Issue by clucani** [azlux/log2ram#171]
Is it as simple as disabling the log2ram service?

**Comment by azlux** [comment]
To disable the service :  
```
systemctl stop log2ram.service log2ram-daily.timer
systemctl disable log2ram.service log2ram-daily.timer
```
To enable it again :
```
systemctl enable log2ram.service log2ram-daily.timer
reboot
```

**Comment by clucani** [comment]
Awesome - thanks!

**Comment by p1r473** [comment]
Thought I saw somewhere
systemctl enable log2ram && systemctl start log2ram && systemctl start syslog.socket && systemctl start rsyslog.service

systemctl disable log2ram && systemctl stop log2ram && systemctl stop syslog.socket && systemctl stop rsyslog.service
