### ISSUE TITLE
journal sub-directory still being used after cleanup of all log2ram volume

### ISSUE THREAD

**Issue by bondskin** [azlux/log2ram#172]
Sadly I had a 100% disk allocation on my log2ram volume.
I fixed it and now 42% utilised.

However, there is still a (new) journal directory which seems to be used and filling up quickly.
pi@raspberrypidns:/var/log/journal/7cae93d2e8f14ee3bd5c3e444cf2b0fc $ ll
insgesamt 32768
-rw-r-----  1 root systemd-journal 8388608  3. Sep 09:23 system@0005cb122e268c7d-45ea072539504f54.journal~
-rw-r-----+ 1 root systemd-journal 8388608  3. Sep 09:42 system.journal
-rw-r-----  1 root systemd-journal 8388608  3. Sep 09:23 user-1000@0005cb12382be226-1cef54ff1d223570.journal~
-rw-r-----+ 1 root systemd-journal 8388608  3. Sep 09:41 user-1000.journal

how can I stop that?

**Comment by azlux** [comment]
Hi,
Please check this Readme section : https://github.com/azlux/log2ram#existing-content-in-varlog-too-large-for-ram
There are specific config for journalctl in your case.

Best regards
Azlux
