### ISSUE TITLE
Changing daily disk write time

### ISSUE THREAD

**Issue by alan-rpi** [azlux/log2ram#177]
Hi. I read your Readme to change the day and time of daily disk write

How would I just change the time to just after midnight (I have some logging that is done just before midnight). 

Would it be this? [ I changed "Mon " to "*-" ]
```
[Timer]
OnCalendar=
OnCalendar= *-*-*-* 00:05:00
```
Many thanks

**Comment by p1r473** [comment]
https://man.archlinux.org/man/systemd.time.7

**Comment by alan-rpi** [comment]
Thanks p1r473 for a very quick and helpful reply. 

I make it:
`*-*-* 00:05:00`

**Comment by azlux** [comment]
good to close ?
