### ISSUE TITLE
can this work with FriendlyWRT / Open/WRT ?

### ISSUE THREAD

**Issue by KalixtShawxo** [azlux/log2ram#180]
simple question...cause the docs say that the script can be used with any Linux.

But I can't seem to get it installed.  I have installed FriendlyWRT on a Nanopi R2S and thought Log2Ram would be a good addition (I use it with my DietPi installs) but SUDO and Systemctl don't exist with FriendlyWRT. 
so following the manual install doesn't work as written and I am too newb to figure out the changes needed.  I did a search in the issues and didn't find anything for the WRT install.  
This is the error I got the first time by removing the SUDO
`root@FriendlyWrt:~/log2ram-master# chmod +x install.sh && ./install.sh
./install.sh: line 3: systemctl: not found
./install.sh: line 8: install: not found
./install.sh: line 9: install: not found
./install.sh: line 10: install: not found
./install.sh: line 11: install: not found
./install.sh: line 12: install: not found
./install.sh: line 13: install: not found
./install.sh: line 14: systemctl: not found
##### edit /etc/log2ram.conf to configure options ####
`
then i replaced SUDO with BASH and got this
`root@FriendlyWrt:~/log2ram-master# bash ./install.sh
./install.sh: line 3: systemctl: command not found
./install.sh: line 8: install: command not found
./install.sh: line 9: install: command not found
./install.sh: line 10: install: command not found
./install.sh: line 11: install: command not found
./install.sh: line 12: install: command not found
./install.sh: line 13: install: command not found
./install.sh: line 14: systemctl: command not found
##### edit /etc/log2ram.conf to configure options ####
`
anyone want to be my hero and tell me what I need to change to make it work? 

thanks in advance for any help.

**Comment by azlux** [comment]
Hi,
1. DietPI is already well optimized with log and write cycle. I don't think you need log2ram. The project manager have create a ["clone" of log2ram into the system](https://github.com/MichaIng/DietPi/blob/1eae2f73a71f34f20aa2c701adde99e72e4b08f5/CHANGELOG.txt#L117)
2. You have standard command (install) not install, it's really a DIETpi :D 
3. you don't have systemctl ? So look like not a systemd system.
