### ISSUE TITLE
[DOC] small change in manual install script

### ISSUE THREAD

**Issue by edgd1er** [azlux/log2ram#181]
thanks for your project

the install step seems to need i little update, as the file is compressed a -z is required in the tar.
```
curl -Lo log2ram.tar.gz https://github.com/azlux/log2ram/archive/master.tar.gz
tar xf log2ram.tar.gz
.....
```
To avoid a file write, keep the file in memory, here is my suggestion
```
curl -L https://github.com/azlux/log2ram/archive/master.tar.gz | tar zxf -
....
```

**Comment by azlux** [comment]
thank
