### ISSUE TITLE
There is no log2ram job in cron.*

### ISSUE THREAD

**Issue by foerster-rwth** [azlux/log2ram#206]
I am running Adguard (and nothing else) on a Raspberry Pi 3B+. Yesterday I installed log2ram, and it seems to work. There is, however, no cron job for log2ram to be found anywhere, see screenshot:

![log2ram-raspberry-pi](https://user-images.githubusercontent.com/72136104/227567406-b2705a71-8d54-4d93-9050-601cc0ddde85.png)

I don't know whether this is really an issue, but I would d like to make sure. The log2ram readme does not mention cron jobs, but everyone else on the internet talking about log2ram states that there would be a default job "log2ram" in cron.daily.

**Comment by azlux** [comment]
Hi,
Log2ram use a systemd timer, no cron here.
You can check that with `systemctl status log2ram-daily.timer`

**Comment by foerster-rwth** [comment]
Thank you!
