### ISSUE TITLE
Buster repo missing

### ISSUE THREAD

**Issue by XhmikosR** [azlux/log2ram#212]
@azlux could you please bring this back?

**Comment by azlux** [comment]
Yes, because it's a oldoldstable release.
Since bookworm have been release, I didn't though buster was needed.

**Comment by xtvdata** [comment]
Indeed it's old stable, but old hardware with limited RAM (where this tool is more important), sometimes it's more efficient to run them on older distributions...

Also Buster is still included in LTS support until "June 30th, 2024" (ref. [Debian website](https://wiki.debian.org/LTS))

**Comment by azlux** [comment]
Hum, ok,
I will rollback my change

**Comment by XhmikosR** [comment]
Yup, thanks!
