### ISSUE TITLE
Why only copy file when using rsync?

### ISSUE THREAD

**Issue by MegaV0lt** [azlux/log2ram#25]
when enabling rsync in the conf it is using the -W switch to copy fiels instead using the delta algo:
`-W, --whole-file            copy files whole (without delta-xfer algorithm)
`
Is there any reason for that. If not using -W it will write less data because of inteligent delta sync.

**Comment by azlux** [comment]
From the man :
This option disables rsync's delta-transfer algorithm, which causes all transferred files to be sent whole. The transfer may be faster if this option is used when the bandwidth between the source and destination machines is higher than the bandwidth to disk (especially when the "disk" is actually a networked filesystem). This is the default when both the source and destination are specified as local paths, but only if no batch-writing option is in effect.

We are in a local machine in our case.
