### ISSUE TITLE
logfile does not get cleaned

### ISSUE THREAD

**Issue by MegaV0lt** [azlux/log2ram#31]
The log2ram.log is increasing in size and does not get cleaned... So after some time is will eat all available space.

My suggestion is to include it in an logrotatescript or handle it internally. Sample (Bash):

> if [[ -e "$LOG" ]] ; then       # Log-Datei umbenennen, wenn zu groß
  FILESIZE="$(stat -c %s "$LOG")"
  [[ $FILESIZE -ge $MAXLOGSIZE ]] && mv --force "$LOG" "${LOG}.old"
fi

**Comment by azlux** [comment]
I don't know about this idea. I think you have lot of log because I forgot to make rsync quiet. (I've keep the  `-v` option)
In the case you want to clean your log, use logrotate. I cannot use your code because I need to keep log2ram Bash and Dash compatible.
Log are cleaned on every reboot.
