### ISSUE TITLE
some warnings from shellcheck

### ISSUE THREAD

**Issue by MegaV0lt** [azlux/log2ram#32]
shellcheck gives some warnings about not quoted vars and similar:
![auswahl_20171009_14 29 24](https://user-images.githubusercontent.com/2804301/31338102-576471d4-acfe-11e7-8d02-2da47888904f.png)

Also it is better to read to write [ -n "$var" ] instead of [ ! -z "$var" ]

**Comment by azlux** [comment]
I need to check that, if the changes are Dash compatible. (I think they are)
Thank for the notice.

**Comment by azlux** [comment]
I think I'm good now.
