### ISSUE TITLE
log2ram.log empty

### ISSUE THREAD

**Issue by AndrewB82** [azlux/log2ram#36]
Hi, I tried to check the service. Apparently it is running:
- df -h - log2ram present,
- mount - log2ram present,
but:
- log2ram.log is empty.

By the way - it is in folder hdd.log , not log.hdd as pointed in readme.

**Comment by azlux** [comment]
Hi,
I use the `cp` function without the option `-v` So you don't have log when there are no error.
I will change the readme, thank for pointing me that.

**Comment by AndrewB82** [comment]
Thanks for clarification - everything is at it should be thereby. Thx!
