### ISSUE TITLE
Suggestion: install uninstaller and remove the source folder then

### ISSUE THREAD

**Issue by thomas-mc-work** [azlux/log2ram#46]
On setup the `uninstaller.sh` should be copied to the target system as well. Then the downloaded and extracted archive could be removed. This way you always know where to find the uninstaller and are prevented from getting lost of it.

The target could be one of these:
- `/usr/local/bin/log2ram-uninstaller.sh`
- `/usr/local/bin/uninstall-log2ram.sh`

Also maybe the uninstaller script could be installed without execution permission to prevent uninstalling by accident.

The Readme could then be updated like this:

## Install

    curl -Lo log2ram.tar.gz https://github.com/azlux/log2ram/archive/master.tar.gz
    tar xf log2ram.tar.gz
    chmod +x log2ram-master/install.sh && sudo log2ram-master/install.sh
    rm -r log2ram-master

…

## Uninstall :(
(Because sometime we need it)

    chmod +x /usr/local/bin/uninstall-log2ram.sh && uninstall-log2ram.sh

**Comment by azlux** [comment]
good point ! I will look at this suggestion.

**Comment by MegaV0lt** [comment]
Bad when you have it downloaded via git clone to keep it actual

**Comment by azlux** [comment]
@MegaV0lt keeping you updated by git clone don't install the product. So I don't think it's a bad idea.
And I think people who clone my project instead of following the Readme know what they do.

**Comment by MegaV0lt** [comment]
I know. The point is when i want to update the installation (I know i have to uninsatll/install) it is bad when the uninstall removes my git-dir. I want to have the git to keep updatet setup files instead to go to some website and download the source manualy.

**Comment by thomas-mc-work** [comment]
> when the uninstall removes my git-dir

Maybe I'm misunderstanding here. But I think the uninstaller only removes the installation, not the setup folder. Actually the whole thing is independent of the distribution of the installer.

**Comment by azlux** [comment]
I've take care of you both comment.
Uninstaller is copy into /usr/local/bin for futur uninstall.
I've add the command to remove the folder of log2ram into the README. The script will not to do itself.

**Comment by heikoh81** [comment]
On your GitHub frontpage, there is 1 error in the installation instructions.

`cd log2ram-master`
 is not needed for
`chmod +x log2ram-master/install.sh && sudo log2ram-master/install.sh`

Even more, cd-ing into the extracted directory produces an error.
This could confuse unexperienced users!

**Comment by azlux** [comment]
https://github.com/azlux/log2ram/commit/644739c9250252ccbc927d84b977c9241daaa41a : fast fix for the `cd` error.
If I remove the `cd` , I need to change the path of all copy of the `install.sh` script.

**Comment by heikoh81** [comment]
Just set up another Raspberry Pi (Jessie).
`chmod +x install.sh && sudo install.sh`
gives me
`root@raspTEST:~/log2ram-master# chmod +x install.sh && sudo install.sh
sudo: install.sh: command not found
`

Entering `./install.sh` works, however.
