### ISSUE TITLE
if condition issue

### ISSUE THREAD

**Issue by underr-ua** [azlux/log2ram#5]
Hi again!
I tried to manually run log2ram with parameter (start/stop/write) and saw:

> /usr/local/bin/log2ram: 35: /usr/local/bin/log2ram: [[: not found

P.S.: It works perfectly when i changed #!/bin/sh to #!/bin/bash

**Comment by azlux** [comment]
/sh is mostly a link to /bash on many system. Which operation system are you on ?

**Comment by azlux** [comment]
Done !
The [[ builtin has been removed for Dash compatibility.

**Comment by underr-ua** [comment]
Debian 8.6.0
