### ISSUE TITLE
Writing log to file every 8 minutes in place of an hour or per day

### ISSUE THREAD

**Issue by HobbytronicsPK** [azlux/log2ram#52]
Hi.

I have installed log2ram according to instructions given.

I am running mosquitto and it is logging to `/var/log/mosquitto/mosquitto.log` every 8-10 minutes in place of an hour. Even I have change the cron to daily `sudo mv /etc/cron.hourly/log2ram /etc/cron.daily/log2ram`

**Comment by azlux** [comment]
The real sdcard write are into /var/hdd.log

The write on /var/log are only in RAM.

Az
