### ISSUE TITLE
Does log2ram write status directly to hdd?

### ISSUE THREAD

**Issue by NickDaly** [azlux/log2ram#6]
If something goes wrong in log2ram's execution, are those error messages (from `cp` and `rsync`) stored anywhere or are they lost to the ether?  It seems like they're lost.

log2ram should redirect the copy's output directly to the disk (to `"${HDD_LOG}log2ram.log"`) so that any errors in log2ram can be diagnosed.  That won't help if the HDD_LOG variable is messed up, but it'll help in all other situations.

**Comment by NickDaly** [comment]
This should be fixed in pull request #7.

**Comment by azlux** [comment]
That is a good idea.
Thank for your help, I will check your work.

**Comment by azlux** [comment]
check the comment of the #7

**Comment by NickDaly** [comment]
Merged and resolved.
