### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by StuartIanNaylor** [azlux/log2ram#69]
ZL2R: Enable zram compatibility (false by default). Check the comment on the config file. See https://github.com/StuartIanNaylor/zram-swap-config to configure a zram space on your raspberry before enable this option.

Doesn't require zram-swap-config or shouldn't, but do suggest taking a look at zram-swap-config as zram-config-0.5.deb is so broken its not true.
zram-swap-config just enables zram swaps and is separate from L2R using a zram drive.
Both are aware of any previous zram devices and just make another after the previous.
I just changed the Conflicts as if systemd runs them at exact same time then they both can see no previous and then conflict.
Shouldn't happen now but bet I can run a start boot and check a 100 times with no conflict then 1st time it will happen elsewhere. Having the conflict in zram-swap-config should be optimal as that service has little in the Before= / After sections of the systemd unit config.
Maybe have a look at https://github.com/StuartIanNaylor/log2zram as its a minimal Log2Ram using zram.

**Comment by azlux** [comment]
Thank,
I will add this comment.
