### ISSUE TITLE
log2ram.service

### ISSUE THREAD

**Issue by StuartIanNaylor** [azlux/log2ram#70]
Description=Log2Ram

I really struggled with journalctl entries and getting systemd to work in the fashion the Before= & After= directives where set.
After much wasted time I think the description should be lower case as changed log2zram and it seemed to make the difference. At least journalctl -u log2zram.service works anyway.
Main problem though seems to be the IgnoreOnIsolate=yes directive which in action seems to mean ignore other service requests totally and with it I can not seem to stop the occasional conflict.
Without out I just ran 293 consecutive boots without a conflict.
As then the After= declaration combined with the Before= of the other service seems to work a treat.

**Comment by azlux** [comment]
The name of the service isn't the same input as the description.
Changing the description will not change anything.
