### ISSUE TITLE
README.md for Arch

### ISSUE THREAD

**Issue by jpearn** [azlux/log2ram#77]
I've just set this up on a couple of old Cubox 1's running Arch Linux. If you could add onto the README.md that Arch uses systemd/Timers by default but installing a cronie as a package 'pacman -S cronie' followed by 'systemctl enable cronie', adds cron timers. All works fine.
Thanks for the useful utility.

**Comment by azlux** [comment]
Feel free to push requests a Readme change, I don't have Arch.

**Comment by azlux** [comment]
related to #84
