### ISSUE TITLE
log2ram.hourly

### ISSUE THREAD

**Issue by phzang** [azlux/log2ram#82]
The instructions:
"By default Log2Ram writes to the HardDisk every hour. If you think this is too much, you can make the write every day by moving the cron file to daily: sudo mv /etc/cron.hourly/log2ram.hourly /etc/cron.daily/log2ram.daily."

On Raspbian GNU/Linux 9 (stretch):

sudo mv /etc/cron.hourly/log2ram.hourly /etc/cron.daily/log2ram.daily
mv: cannot stat '/etc/cron.hourly/log2ram.hourly': No such file or directory

In install.sh: "15 install -m 755 log2ram.hourly /etc/cron.hourly/log2ram"  

There's no log2ram.hourly file created, only log2ram in /etc/cron.hourly by default.  Shouldn't the instructions read:

"...If you think this is too much, you can make the write every day by moving the cron file to daily: sudo mv /etc/cron.hourly/log2ram /etc/cron.daily/log2ram."  ?

or in install.sh line 15 "install -m 755 log2ram.hourly /etc/cron.hourly/log2ram.hourly" ?

**Comment by azlux** [comment]
Hi,
I will fix the instructions. Thank for the report.
