### ISSUE TITLE
RAM disk too small (raspberry zero W)

### ISSUE THREAD

**Issue by kiai72** [azlux/log2ram#95]
hello,
everything works fine on my RPI3B+ - but not on my raspberry zero W.

./install.sh does not report any errors, but after reboot i don't see the partition (neither in mount, nor df -h).

so i tried:
 pi@raspberrypi:~/log2ram $ sudo /usr/local/bin/log2ram start
ERROR: RAM disk too small. Can't sync.

**Comment by azlux** [comment]
please refer to this issue : https://github.com/azlux/log2ram/issues/90

Az

**Comment by kiai72** [comment]
thank you - works! i had to set it to 120M
