### ISSUE TITLE
What if I want another path ?

### ISSUE THREAD

**Issue by Vartkat** [azlux/log2ram#96]
Hi,

I'm using Home Assistant and would like to include on the RamDisk another path than /var/log, in my case the Home Asistant db file which is in /config. Is that possible ?
Another question would be how to force dump the memory to disk from command line ?

Thanks for your help

Regards
V.

**Comment by azlux** [comment]
Hi,
Please upvote this issue if you want this feature.

The following two lines do the path config : https://github.com/azlux/log2ram/blob/master/log2ram#L5-L6

I will Pin this issue and check if people want to have custom folder.

**Comment by cmonty14** [comment]
Hi,
I'm facing a very similar issue running [OSMC](https://osmc.tv/) on Raspi 3.
OSMC writes Kodi logfile to _/home/osmc/.kodi/temp/kodi.log_.

Therefore I'm supporting this feature request.

However I want to discuss another workaround and address this question here:
If I create a bind mount `mount --bind /home/osmc/.kodi/temp/ /var/log/kodi`, will this ensure that any write IO goes to ramlog disk only? Or will the write IO go to both directories, _/home/osmc/.kodi/temp/_ and _/var/log/kodi_? In the later case, this is no workaround.

THX

**Comment by xtvdata** [comment]
I have a similar need to reduce I/O on cacti rdd files (which is much higher than I/O from logging).

**Comment by pierrotori** [comment]
ok thank you but if i add a specifique directory , i duplicate log2ram.conf or i add a variable RAM_LOG2 ?

**Comment by azlux** [comment]
this have been commited. You can test it.
I will release this feature after few days without issue.

**Comment by azlux** [comment]
After 2 week with no error reported, I think I will release this feature in the next stable version incoming this week.
