### ISSUE TITLE
Question (not an issue)

### ISSUE THREAD

**Issue by nbenm** [azlux/log2ram#98]
Isn't it better to use `rsync --append` to minimize writing ?

**Comment by azlux** [comment]
It's was the case before : https://github.com/azlux/log2ram/commit/0dc5827f5c7a0d38a505a3d8907bb1d4df82e2f7
After some issues https://github.com/azlux/log2ram/issues/92 and discussions with rsync team, new files and logrotate can conflict with `--append` command
