### ISSUE TITLE
syncFromDisk should use $LOG_DISK_SIZE instead of $SIZE

### ISSUE THREAD

**Issue by cotchon** [azlux/log2ram#99]
HDD_LOG is compared to $SIZE to check if the logs fits into the newly zram created.
But $SIZE is the mem_limit of zram (physically).
HDD_LOG should be compared to $LOG_DISK_SIZE instead of $SIZE since it is the disk size of the zram. 
proposal :
    if [ ! -z "$(du -sh -t "$SIZE" $HDD_LOG/ | cut -f1)" ]; then
    if [ ! -z "$(du -sh -t "$LOG_DISK_SIZE" $HDD_LOG/ | cut -f1)" ]; then

**Comment by azlux** [comment]
You're right, In case of zram, I need to check `$LOG_DISK_SIZE`. I will add another condition.
Thank for the report

**Comment by azlux** [comment]
I've some issue on zram for now, are you have to make a pull requests ?

**Comment by cotchon** [comment]
Sorry, can you explain what is a pull request please ?

**Comment by azlux** [comment]
Github have some explicating into their wiki : https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
The goal is to send me the changes you have done into your fork, to be merge into this project.

**Comment by cotchon** [comment]
I can not create a branch on the projet, but I replaced in log2ram the following line : 
26:     if [ ! -z "$(du -sh -t "$SIZE" $HDD_LOG/ | cut -f1)" ]; then
by:
26:    if [ ! -z "$(du -sh -t "$LOG_DISK_SIZE" $HDD_LOG/ | cut -f1)" ]; then

**Comment by azlux** [comment]
ok, I will do that.
Thank

**Comment by azlux** [comment]
Should be fixed on https://github.com/azlux/log2ram/commit/881eea145f8393c17cb0b18f4b6113cf1a1cc96d
